### ISSUE TITLE
Problems creating a service from Albatros

### ISSUE THREAD

**Issue by dixonmartinez** [dcylabs/albatros#1]
Greetings...
With the new version of albatross I have problems starting the services.

This comes after at least two minutes after the service started. I've been working with this tool since January with version 0.3.0 to version 0.4.0 actualize and my services stopped working.

Do not attach a log albatross because the application does not give me any information of what happens ...

Can you tell me where I can see a log albatross to guide me in finding my mistake?

**Comment by dcylabs** [comment]
Hello, 

Do you use it behind a proxy like haproxy ? If so you should add `option http-pretend-keepalive` to your backend configuration. 
Is the albatros container up and running when doing `docker ps -a | grep albatros` ?
Can you post your _docker-compose.yml_ or how you run it through command line ? 
Maybe there is a mistake in the _config.json_, can you post it too (remove all passwords and secret before posting it)

With all your informations I will dig into it to find what's going wrong.

**Comment by dcylabs** [comment]
Closed due to no answer
