### ISSUE TITLE
Config using ENV Vars?

### ISSUE THREAD

**Issue by psi-4ward** [dcylabs/albatros#2]
(For me) It would be much easier to use some `env` Vars (in docker run) to configure Albatros than deploying a `config.json`.

```
docker run \
  -e "USER[1]=user1" \
  -e "PASSWORD[1]=verysecret"  \
  -e USE_SSL=no \
  -p 80:80 dcylabs/albatros
```

Perhaps you can add some support for this?
Whats your opinion about this feature?

**Comment by dcylabs** [comment]
I will look into it on this week-end. But at a first look it disturbs me to have passwords stored in environment variables. 

Do you consider using a _minimalist_ version of the `config.json` file would be an improvement ? (see example)

**PS:** I think to add some cryptography to improve password security with some algorithms and provide a command to encrypt password like : 
`docker run --rm -ti dcylabs/albatros /var/albatros/encrypt mypassword`
output: 
`abcdef0123...456789`

## Example

### Default config embedded in the Albatros image :

```
{
    "DockerEndpoint": "/var/run/docker.sock",
    "ListenHTTP"    : ":80",
    "ListenHTTPS"   : ":443",
    "SSLKeyPath"    : "/var/albatros/key.pem",
    "SSLCertPath"   : "/var/albatros/cert.pem",
    "AppPath"       : "/var/albatros/ui/build",
    "Secret"        : "thisisasecretreplaceit",
    "SessionTime"   : 600,
    "UseSSL"        : true,
    "Accounts"      : []
}
```

##### with a custom _config.json_

```
{ 
    "UseSSL" : false,
    "Accounts"        : [
        {
            "Username"    : "user1",
            "Password"    : "verysecret"
        }
    ]
}
```

### Would result in :

```
{
    "DockerEndpoint": "/var/run/docker.sock",
    "ListenHTTP"    : ":80",
    "ListenHTTPS"   : ":443",
    "SSLKeyPath"    : "/var/albatros/key.pem",
    "SSLCertPath"   : "/var/albatros/cert.pem",
    "AppPath"       : "/var/albatros/ui/build",
    "Secret"        : "thisisasecretreplaceit",
    "SessionTime"   : 600,
    "UseSSL"        : false,
    "Accounts"      : [
        {
            "Username"    : "user1",
            "Password"    : "verysecret"
        }
    ]
}
```

**Comment by psi-4ward** [comment]
The current use case is to start the Container using systemd.
We have different services like Postgres, MariaDB, Icinga and others, all configured entirly through ENV-Vars. So its important to take care about accessing these files.
Nevertheless, if anyone compromises the host-system, he has access to almost _everything_.
If someone compromise the container itslef, he can access the config.json. 
So for me it depends on the security level to use env-vars for passwords. In our use-case its only a bit simpler to deploy the albatros container.

**Comment by dcylabs** [comment]
I thought about it this week and I finally concluded that you're right: configuration through environment variables are more common and usable ways but not less secure for containers than json files.

I will soon release the 0.5.0 to include this modification. Also, I will add some algorithms (I don't know what at the time) to have passwords encrypted so environment variables are not clearly exposed in container configurations.

**Comment by psi-4ward** [comment]
Very nice solution! Thanks !
